# Generated by Django 4.2.11 on 2024-09-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city_of_origin",
            field=models.CharField(
                default="Békéscsaba", max_length=180, verbose_name="City"
            ),
        ),
    ]
